name: cyclone
description: "animal fattening automation application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pinput: ^2.2.21

  cupertino_icons: ^1.0.8
  flutter_carousel_widget: ^3.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.5
  dropdown_button2: ^2.3.9
  deepseek: ^1.2.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  deepseek_api: ^0.1.0
  firebase_database: ^11.3.5
  flutter_localization: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/beef.svg
    - assets/bull.svg
    - assets/goat.svg
    - assets/sheep.svg
    - assets/icons/menu.svg
    - assets/icons/home.svg
    - assets/icons/home_b.svg
    - assets/icons/shop.svg
    - assets/icons/shop_w.svg
    - assets/icons/mesages.svg
    - assets/icons/food.svg
    - assets/icons/logo.svg
    - assets/icons/chat.svg
    - assets/Social/facebook.svg
    - assets/Social/whatsaap.svg
    - assets/Social/Google.svg
    - assets/person.png
    - assets/principles.png
    - assets/icons/goat_id.svg
    - assets/icons/beef_id.svg
    - assets/icons/sheep_id.svg
    - assets/icons/table.svg
    - assets/icons/animal_info.svg
    - assets/korm.png
    - assets/ector.svg
    - assets/pass.svg
    - assets/money.svg
    - assets/one.svg
    - assets/icons/x.svg
    - assets/alina.png
    - assets/icons/mesages_w.svg
    - assets/icons/visa_logo.png
    - assets/icons/jazzcash_logo.png
    - assets/icons/mastercard_logo.png
    - assets/visa_cart.png
    - assets/pattern.png
    - assets/icons/pen.svg
    - assets/icons/create.svg
    - assets/icons/stern.svg
    - assets/icons/one.svg
    - assets/icons/bull_id.svg

  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf


